### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by matthewmayer** [OSSPhilippines/paymongo#41]
Is there an easy way to see what changes were made from 1.1.1 to 1.2.x? 

The latest Github release tag is from https://github.com/jofftiquez/paymongo/releases/tag/v1.0.4 and the page at https://jofftiquez.gitbook.io/paymongo/change-logs seems outdated.

**Comment by jofftiquez** [comment]
> Is there an easy way to see what changes were made from 1.1.1 to 1.2.x?
> 
> The latest Github release tag is from https://github.com/jofftiquez/paymongo/releases/tag/v1.0.4 and the page at https://jofftiquez.gitbook.io/paymongo/change-logs seems outdated.

Good catch @matthewmayer I will update the change logs as soon as I possible. Thank you.

**Comment by jofftiquez** [comment]
Moving forward we will be using releases to record change log and add them [in this page](https://paymongo.ossph.org/change-logs#2023-05-12). Thanks
